name: flatpak-ci

on:
  push:
  pull_request:

jobs:
  flatpak:
    name: "Flatpak ${{ matrix.arch }}"
    runs-on: ${{ matrix.runner }}

    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-50
      options: --privileged

    strategy:
      matrix:
        include:
          - arch: x86_64
            runner: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Build Flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: throwdown-${{ matrix.arch }}.flatpak
          manifest-path: io.github.yioannides.Throwdown.json
          cache-key: flatpak-builder-${{ matrix.arch }}-${{ github.sha }}
          arch: ${{ matrix.arch }}

      - name: Upload Flatpak artifact
        uses: actions/upload-artifact@v4
        with:
          name: throwdown-${{ matrix.arch }}
          path: throwdown-${{ matrix.arch }}.flatpak
